# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='body',
        ),
    ]
