# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160217_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messages',
            new_name='message',
        ),
    ]
